### ISSUE TITLE
Installer wizard returns a Python error in validate_scripts

### ISSUE THREAD

**Issue by hassebylov** [balsamiq/balsamiq-wireframes-linux#7]
Platform: **Ubuntu 20.10**
Version: **Lutris 0.5.8**

### Steps to reproduce
Execute the following in a terminal:
1. `wget https://raw.githubusercontent.com/balsamiq/balsamiq-wireframes-linux/master/bw.yml -O /tmp/bw.yml`
2. `lutris -i /tmp/bw.yml`

### Expected behavior
I'd want to "... follow the steps in the Lutris wizard, and voila'!"

### Actual behavior
Main window of Lutris application opens. Additionally, a dialog with two buttons (Cache and Cancel) is shown, but with no content.

Terminal returns:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 456, in do_command_line
    self.show_installer_window(installers)
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 252, in show_installer_window
    self.show_window(
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 246, in show_window
    window_inst = window_class(application=self, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 97, in __init__
    self.choose_installer()
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 123, in choose_installer
    self.validate_scripts()
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 115, in validate_scripts
    script[item] = script.get(item) or ""
AttributeError: 'str' object has no attribute 'get'

**Comment by balsamiqGozzi** [comment]
it seems a regression wrt lutris 5.8 (works fine in lutris 5.7.x) i'm investigating

**Comment by balsamiqGozzi** [comment]
please try now with 
lutris -i "https://raw.githubusercontent.com/balsamiq/balsamiq-wireframes-linux/master/balsamiq-wireframes-installer.json"

it should work

**Comment by hassebylov** [comment]
Thanks @balsamiqGozzi, problem solved.
